import type { Metadata } from "next";
import "./globals.css";
import 'swiper/css';
import 'rsuite/dist/rsuite-no-reset.min.css';


export const metadata: Metadata = {
  title: "Create Next App",
  icons: {
    icon: "/favicon.ico",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={``}>{children}</body>
    </html>
  );
}
